<a href="https://colab.research.google.com/github/ayushi-2310/Ayushi-DAML-2021-22/blob/main/HET.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def clean(l):
  t=[]
  for i in l:
    if '-' in i:
      i=i.split('-')
      a= (int(i[0])+int(i[1]))/2
      t.append(a)
    elif i.endswith('yards'):
      a =float((i[0:i.index('y')])*9)
      t.append(a)
    elif i.endswith('sq.m'):
      a= float(i[0:i.index('s')])*10.7639
      t.append(a)
    elif i.endswith('cent'):
      a= float(i[0:i.index('c')])*435.56
      t.append(a)
    elif i.endswith('guntha'):
      a= float(i[0:i.index('g')])*1088.999963702 
      t.append(a)
    elif i.endswith('squaremetre'):
      a= float(i[0:i.index('s')])*10.7639
      t.append(a)
  return t
o=['100-110','200yards','400sq.m','50cent','38guntha','600squaremetre'  ]
clean(o)

  

[105.0,
 2.002002002002002e+26,
 4305.5599999999995,
 21778.0,
 41381.998620676,
 6458.34]

In [1]:
import numpy as np


In [ ]:
myarray=np.array("Ayushi")

In [ ]:
myarray

array('Ayushi', dtype='<U6')

In [ ]:
np.__version__

'1.19.5'

In [ ]:
x=np.array(300)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x

array(300)

In [ ]:
oned=np.array([12,34,56,78,90])
oned

array([12, 34, 56, 78, 90])

In [ ]:
type(oned)

numpy.ndarray

In [ ]:
oned.ndim

1

In [ ]:
oned.size

5

In [ ]:
oned.shape

(5,)

In [ ]:
twod=np.array([[1,2,3],[23,34,45],[1,1,1]])
twod

array([[ 1,  2,  3],
       [23, 34, 45],
       [ 1,  1,  1]])

In [ ]:
twod.ndim

2

In [ ]:
twod.size

9

In [ ]:
twod.shape

(3, 3)

Creating nday array with zeros 

In [ ]:
zero=np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
z=np.zeros(10,dtype=np.int8)
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

#Create an array of 2X3 having zeros

In [ ]:
z=np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ones=np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
ones=np.ones((2,3,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
ones.ndim

3

In [ ]:
import sys
l=[1,2,3,4,5,6,7,8,9]
print(sys.getsizeof(1)*len(l))
arr=np.array(l)
print(arr.size*arr.itemsize)

252
72


In [ ]:
l=[1000,[12,98]]
sys.getsizeof(l)

88

In [ ]:
x=np.random.rand(10)
x

array([0.48822866, 0.23828584, 0.86102669, 0.85112038, 0.38778489,
       0.58890263, 0.1164453 , 0.49027326, 0.88078268, 0.67814526])

In [ ]:
x=np.random.rand(3,4)
x

array([[0.21774958, 0.80391975, 0.48959936, 0.84421498],
       [0.17296952, 0.33921515, 0.30350327, 0.19892046],
       [0.07534545, 0.26761169, 0.87000985, 0.05185521]])

In [ ]:
x=np.random.randint(5,11,size=10)
x

array([ 6,  7,  5,  5,  5,  6,  6, 10,  8,  5])

In [ ]:
x=np.random.randint(5,10,size=(3,2))
x

array([[5, 7],
       [6, 8],
       [7, 8]])

In [ ]:
l=[1,2,3,4,5,6,7,8]
x=np.random.choice(l)
x

2

In [ ]:
l=['Mon','Tue','Wed','Thurs','Fri']
x=np.random.choice(l,size=3)
x

array(['Mon', 'Mon', 'Tue'], dtype='<U5')

In [ ]:
x=np.random.choice(l,size=(4,3))
x

array([['Thurs', 'Mon', 'Fri'],
       ['Thurs', 'Tue', 'Wed'],
       ['Tue', 'Thurs', 'Thurs'],
       ['Tue', 'Mon', 'Tue']], dtype='<U5')

In [ ]:
x=np.array([10,23,45,67,89])
x[1]

23

In [ ]:
y=np.array([[10,23,45,67],[2,4,6,7],[3,5,7,9]])
y[1,2]

6

In [ ]:
x=np.array([10,23,45,67,89])
x[1:3]


array([23, 45])

In [ ]:
x=np.array([10,23,45,67,89])
x[3:1]

array([], dtype=int64)

In [ ]:
x=np.array([[12,3,4],[2,4,6],[4,3,7],[6,7,9]])
x[1:3]

array([[2, 4, 6],
       [4, 3, 7]])

In [ ]:
x[-1:]

array([[6, 7, 9]])

In [ ]:
x[:3]

array([[12,  3,  4],
       [ 2,  4,  6],
       [ 4,  3,  7]])

In [ ]:
x[:,1:]

array([[3, 4],
       [4, 6],
       [3, 7],
       [7, 9]])

In [ ]:
x[0:2,1:]

array([[3, 4],
       [4, 6]])

In [ ]:
x=np.array([10,23,45,67,89])
x%5==0

array([ True, False,  True, False, False])

In [ ]:
x=np.array([10,23,45,67,89])
x[x%5==0]

array([10, 45])

In [ ]:
x=np.array([[12,3,4],[2,4,6],[4,3,7],[6,7,9]])
x[x%2==0]

array([12,  4,  2,  4,  6,  4,  6])

#Fancy Indexing

In [ ]:
x=np.random.randint(100,size=(10,6))
x

array([[25, 53, 79, 95, 42, 51],
       [53,  4, 23, 84, 31, 72],
       [40, 52, 59, 29, 53, 51],
       [43, 51, 29,  3, 35, 51],
       [56, 36, 26, 14, 17, 87],
       [ 3,  0, 19, 22, 56, 15],
       [19, 30, 72,  0, 60, 91],
       [37, 21,  4, 56,  3, 24],
       [65, 64, 71, 93, 91, 87],
       [30, 36, 42, 35, 18, 23]])

In [ ]:
x[:,[1,3,5]]

array([[53, 95, 51],
       [ 4, 84, 72],
       [52, 29, 51],
       [51,  3, 51],
       [36, 14, 87],
       [ 0, 22, 15],
       [30,  0, 91],
       [21, 56, 24],
       [64, 93, 87],
       [36, 35, 23]])

In [ ]:
x[:,[5,2,5]]

array([[51, 79, 51],
       [72, 23, 72],
       [51, 59, 51],
       [51, 29, 51],
       [87, 26, 87],
       [15, 19, 15],
       [91, 72, 91],
       [24,  4, 24],
       [87, 71, 87],
       [23, 42, 23]])

In [ ]:
x[2:6,[5]]

array([[51],
       [51],
       [87],
       [15]])

In [ ]:
x[2:7,[4,5]]

array([[53, 51],
       [35, 51],
       [17, 87],
       [56, 15],
       [60, 91]])

In [ ]:
x[2:5][:,3:]

array([[29, 53, 51],
       [ 3, 35, 51],
       [14, 17, 87]])

#Reshaping of arrays

In [ ]:
n=np.arange(1,10)
n.reshape(3,3)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
n=np.arange(1,10)
n.reshape(3,3).base

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
n=np.arange(1,10)
n.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
m=np.array([[1,2],[2,3],[3,4]])
m

array([[1, 2],
       [2, 3],
       [3, 4]])

In [ ]:
np.rot90(m,2)

array([[4, 3],
       [3, 2],
       [2, 1]])

In [ ]:
x=np.array([[1,2,3],[3,4,5],[3,5,7]])
y=np.array([[2,2,2],[3,3,3],[5,5,5]])
np.concatenate([x,y],axis=0)
#column should be equal

array([[1, 2, 3],
       [3, 4, 5],
       [3, 5, 7],
       [2, 2, 2],
       [3, 3, 3],
       [5, 5, 5]])

In [ ]:
x=np.array([[1,2,3],[3,4,5],[3,5,7]])
y=np.array([[2,2,2],[3,3,3],[5,5,5]])
np.concatenate([x,y],axis=1)
#row should be equal

array([[1, 2, 3, 2, 2, 2],
       [3, 4, 5, 3, 3, 3],
       [3, 5, 7, 5, 5, 5]])

In [ ]:
x=np.array([[1,2,3],[3,4,5],[3,5,7]])
y=np.array([[2,2,2],[3,3,3],[5,5,5]])
np.vstack([x,y])

array([[1, 2, 3],
       [3, 4, 5],
       [3, 5, 7],
       [2, 2, 2],
       [3, 3, 3],
       [5, 5, 5]])

In [ ]:
x=np.array([[1,2,3],[3,4,5],[3,5,7]])
y=np.array([[2,2,2],[3,3,3],[5,5,5]])
np.hstack([x,y])

array([[1, 2, 3, 2, 2, 2],
       [3, 4, 5, 3, 3, 3],
       [3, 5, 7, 5, 5, 5]])

Splitting of array

In [ ]:
x= np.arange(1,10)
np.split(x,3) #single value passed so in equal parts will be divided
#division should be equal

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [ ]:
x= np.arange(1,10)
np.split(x,[3,5,6])
#split [0:3],[3:5],[5:6],[6:]

[array([1, 2, 3]), array([4, 5]), array([6]), array([7, 8, 9])]

In [ ]:
x= np.arange(1,10).reshape([3,3])
np.hsplit(x,3)

[array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]]), array([[3],
        [6],
        [9]])]

In [ ]:
x= np.arange(1,11).reshape([2,5])
print(x)
np.hsplit(x,[2,5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


[array([[1, 2],
        [6, 7]]), array([[ 3,  4,  5],
        [ 8,  9, 10]]), array([], shape=(2, 0), dtype=int64)]

In [ ]:
x= np.arange(1,11).reshape([5,2])
print(x)
np.vsplit(x,[3]) #here value is passed in square bracket so splitting will be from [0:3],[3:]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


[array([[1, 2],
        [3, 4],
        [5, 6]]), array([[ 7,  8],
        [ 9, 10]])]

In [ ]:
x=np.array([1,2,3,4])
x.dtype

dtype('int64')

In [ ]:
x=np.array([99999999999999999999999,1,2,3,4])
x.dtype

dtype('O')

In [ ]:
x=np.array([1,2,3,4])
y=x.astype(np.float64)
y

array([1., 2., 3., 4.])

In [ ]:
x=np.array([1.2,3.4])
y=x.astype(np.float32)
y

array([1.2, 3.4], dtype=float32)

Absolute Value

In [2]:
x=np.array([-2,-1,0,1,2])
np.absolute(x)

array([2, 1, 0, 1, 2])

In [3]:
x=[1,2,3]
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

*Logarithmic for normalisation

In [4]:
x=[1,2,3]
np.exp2(x)

array([2., 4., 8.])

In [5]:
x=[1,2,3]
np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [6]:
x=[1,2,3]
np.log2(x)

array([0.       , 1.       , 1.5849625])

In [8]:
x=np.arange(5)
y=np.empty(5)
np.multiply(x,10,out=y)

array([ 0., 10., 20., 30., 40.])

In [9]:
x=np.arange(1,11)
np.add.reduce(x)
#reduce add all element in single array

55

In [10]:
np.add.accumulate(x)
#shows intermediate result

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [12]:
#sum of single array=sum or reduce
np.sum(x)
np.prod(x)

3628800

*mean=median (data symmetrical)

In [13]:
def myufunc(x):
  return x**3

In [16]:
x=np.arange(1,11)
cube=np.frompyfunc(myufunc,1,1)
cube(x)

array([1, 8, 27, 64, 125, 216, 343, 512, 729, 1000], dtype=object)

In [17]:
type(cube)

numpy.ufunc

In [18]:
type(myufunc)

function

In [19]:
#Write a universal function which return true if no is even otherwise return false
def fun(x):
  if x%2==0:
    return True
  else:
    return False

In [23]:
x=np.arange(1,12)
evod=np.frompyfunc(fun,1,1)
evod(x)

array([False, True, False, True, False, True, False, True, False, True,
       False], dtype=object)

In [24]:
def abc(x,y):
  return x*y

In [25]:
glo=np.frompyfunc(abc,2,1)
glo(4,2)

8

In [28]:
data=np.random.randint(10,100,(10,4))
data

array([[41, 10, 47, 54],
       [49, 13, 94, 76],
       [65, 40, 41, 16],
       [80, 38, 24, 21],
       [42, 17, 37, 53],
       [13, 67, 49, 39],
       [52, 87, 19, 40],
       [16, 51, 15, 42],
       [23, 69, 66, 20],
       [72, 55, 15, 15]])

In [29]:
np.sort(data,axis=0)

array([[13, 10, 15, 15],
       [16, 13, 15, 16],
       [23, 17, 19, 20],
       [41, 38, 24, 21],
       [42, 40, 37, 39],
       [49, 51, 41, 40],
       [52, 55, 47, 42],
       [65, 67, 49, 53],
       [72, 69, 66, 54],
       [80, 87, 94, 76]])

In [30]:
np.sort(data[:,[1]],axis=0)

array([[10],
       [13],
       [17],
       [38],
       [40],
       [51],
       [55],
       [67],
       [69],
       [87]])

In [35]:
x=np.array([1,2,3,5,6])
f=[True,False,True,True,False]
x[f]

array([1, 3, 5])

In [36]:
x=np.array([1,2,3,5,6])
f=x%2==1
x[f]

array([1, 3, 5])